### ISSUE TITLE
Missing "Tools" title in project description

### ISSUE THREAD

**Issue by slava-nat** [expertanalytics/cvcreator#106]
<img src="https://github.com/expertanalytics/cvcreator/assets/63230192/88f362d6-5bf9-4946-bf1a-314393405629" width="400" height="auto">
<img src="https://github.com/expertanalytics/cvcreator/assets/63230192/b1dcca47-a634-4a36-8b83-207143f2c802" width="400" height="auto">

# Problem

I noticed that the "Tools" title in project descriptions is missing in the current version of `cvcreator` (see screenshots above).  In the previous versions, such as `1.1.12`, the titles are rendered correctly. 

# Steps to replicate:
1. Create a file `example.toml` with the following content:
    ```toml
    name = "Alice Green"

    [[project]]
    activity = "project name"
    description = "long description"
    tools = "Python, ..."
    ```
2. Install version `1.1.14` of `cvcreator`:
    ```bash
    pip install cvcreator==1.1.14
    ```
3. Create a PDF using the flag to include all projects:
    ```bash
    cv create example.toml example.pdf --projects :
    ```

## Possible reason

I see that recently a feature was added, which allows to create a PDF with Norwegian titles. The problem is maybe somewhere there. By the way, creating a CV with `--norwegian` flag results in a PDF with correct Norwegian titles, but the "Tools" title is again missing.
