### ISSUE TITLE
Add template for generating aggregated CV output.pdf

### ISSUE THREAD

**Issue by kememil** [expertanalytics/cvcreator#22]
Proposed output:

Header: Expert analytics

Summary: General description of XAL. Stored in a separate yaml-file.

Technical skills:

Scientific: List all. Alternatively present number of consultants with the relevant experience.
Frameworks: List all
Languages: List all
Tools: List all

Extended descriptions of selected projects: Tag relevant projects with XAL

**Comment by jonathf** [comment]
I propose that we first convert the yaml format to a new specification.

From the `example.yaml` we have:
```yaml
Basic:
    Name:  "name"
    Address: "address"
    Post: "zip/post + city"
    Birth: "birthdate"
    Email: "email adresse"
    Phone: "phone number"
Summary: >
    a short description of who you are
    over multiple line if you wanna.
Skills:
    Languages:
        - "programming language"
        - ...
```

I suggest we merge multiple of these together into something like:
```
Basic:
	Name: ["name1", "name2", ...]
	Address: ["address1", "address2", ...]
	...
Summary:
	- "summary1"
	- "summary2"
	...
Skills:
	Languages: ["language1", "language2", ...]
...
```
We remove duplicates, so not the same item is repeated.

Doing first a YAML conversion like this means we can mostly use the same machinery as before to do the parsing. And the specific proposal also means that the template do not need to change very much, as we only need to support one extra layer to the YAML.

@kememil, I can make the conversion machinery if you like.
