### ISSUE TITLE
RFC: Updating the user source files

### ISSUE THREAD

**Issue by jonathf** [expertanalytics/cvcreator#42]
The code for converting our yaml source files to latex code is messy because the yaml is nested with lots of different structures. This has forced the code to solve everything recursively and with lots of edge case handling.

Consider the example:
```yaml
Summary: >                   # one level string
    Some long description
Basic:
    name: Jonathan           # two level string
Languages:
    Norwegian: Fluent        # two level string with indeterminant key
Skill:
    Language: [Bash, C]      # two level list with indeterminant key
Education:
    - [2015, "PhD"]          # one level list of 2-tuple

Work:
    - [2016, "", Consultant] # one level list of 3-tuple
Interests:
    Personal:
        - Traveling          # two level sometimes list sometimes string
Projects:
    A1:
        Activity: Vipps
        Role: Senior Developer
        Staffing: 20 devs
        Period: 2016 -- 2020
        Description: ML      # three level string
```
As long as we keep this format, cleaning up the code is going to be hard.
So lets clean it up and make it as flat. For example for the yaml above:

```yaml
summary: >
    Some long description
name:                   Jonathan
language1_key:          Norwegian
language1_value:        Fluent
skillgroup1_key:        Language
skillgroup1_value:      [Bash, C]
education1:             [2015, "PhD"]
work1:                  [2016, "", Consultant]
project1_activity:      Vipps
project1_role:          Senior Developer
project1_staffing:      20 devs
project1_period:        2016 -- 2020
project1_description:   ML
```

Things to note here:
* Making a script converting from one to the other should be trivial.
* YAML is super feature rich, and though not that important, replacing the fileformat with e.g. TOML or INI might be a good idea as it gives a stronger visual indicator of a switch.
* Making a new latex template target becomes super simple as a template can now be made super simple using Python f-string.
